name: Test Publish to PyPI
on:
  push:
    tags:
      - '*.*.*'

jobs:
  test-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - uses: snok/install-poetry@v1
      - uses: actions/checkout@v2
      - run: poetry config repositories.testpypi https://test.pypi.org/legacy/
      - run: poetry config pypi-token.testpypi "${{ secrets.TEST_PYPI_API_KEY }}"
      - name: publish package (test)
        run: poetry publish --build -r testpypi
